var pic = document.getElementById("pic");
var myName = document.getElementById("myname");
var designation = document.getElementById("designation");
var phone = document.getElementById("phone");
var email = document.getElementById("email");
var address = document.getElementById("address");
var linkedin = document.getElementById("linkedin");
var univesrsity = document.getElementById("university");
var degree = document.getElementById("degree");
var startyear = document.getElementById("startyear");
var college = document.getElementById("college");
var degree1 = document.getElementById("degree1");
var startyear1 = document.getElementById("startyear1");
var company = document.getElementById("company");
var startyear2 = document.getElementById("startyear2");
var description = document.getElementById("description");
var profile = document.getElementById("profile");
var skill1 = document.getElementById("skill1");
var skill2 = document.getElementById("skill2");
var skill3 = document.getElementById("skill3");
var skill4 = document.getElementById("skill4");
var institute = document.getElementById("institute");
var course = document.getElementById("course");
var institute2 = document.getElementById("institute2");
var course2 = document.getElementById("course2");
var language1 = document.getElementById("language1");
var language2 = document.getElementById("language2");
var submitbtn = document.getElementById("submitbtn");
var form = document.getElementById("resumeform");
form === null || form === void 0 ? void 0 : form.addEventListener('submit', function (e) {
    e.preventDefault();
    localStorage.setItem("myname", myName.value);
    localStorage.setItem("designation", designation.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("address", address.value);
    localStorage.setItem("linkedin", linkedin.value);
    localStorage.setItem("university", univesrsity.value);
    localStorage.setItem("degree", degree.value);
    localStorage.setItem("startyear", startyear.value);
    localStorage.setItem("college", college.value);
    localStorage.setItem("degree1", degree1.value);
    localStorage.setItem("startyear1", startyear1.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("startyear2", startyear2.value);
    localStorage.setItem("description", description.value);
    localStorage.setItem("profile", profile.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("skill4", skill4.value);
    localStorage.setItem("institute", institute.value);
    localStorage.setItem("course", course.value);
    localStorage.setItem("institute2", institute2.value);
    localStorage.setItem("course2", course2.value);
    localStorage.setItem("lang1", language1.value);
    localStorage.setItem("lang2", language2.value);
    if (pic.files && pic.files[0]) {
        var reader_1 = new FileReader();
        reader_1.addEventListener("load", function () {
            var textimg = reader_1.result;
            localStorage.setItem("profile-picture", textimg);
        });
        reader_1.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume.html";
});
